### ISSUE TITLE
Use Inviwo:s own Python-app

### ISSUE THREAD

**Issue by ofaismail** [rartino/ENVISIoN#2]
I went through the Inviwo [changelog](https://github.com/inviwo/inviwo/blob/master/CHANGELOG.md) and it seems like they updated the inviwopy API to make it usable straight from Python. With this update, the C++ application created in the 2019 project is no longer needed.

To create a new ENVISIoN application using the new API doesn't seem difficult. Follow the example in the Inviwo changelog from 2019-04-30.

**Comment by jjeessppeer** [comment]
As of version 2.0.0 this is done.
